VAR_test1: def1

VAR_test2:
  - def2-1
  - def2-2
  - def2-3

VAR_test3:
  - test3_1:
    test3_2:
    test3_3:

VAR_test4:
  - test4_1: def4-1
    test4_2:
      - test4_2_1: def4-2-1
        test4_2_2:
          - test4_2_2_1: def4-2-2-1
            test4_2_2_2:
              - test4_2_2_2_1: def4-2-2-2-1_1
                test4_2_2_2_2: def4-2-2-2-2_1
              - test4_2_2_2_1: def4-2-2-2-1_2
                test4_2_2_2_2: def4-2-2-2-2_2


VAR_test5:
  - VAR_hoge1:
    VAR_hoge2:
    VAR_hoge3:

VAR_test6:
    VAR_hoge1: def2-1
    VAR_hoge2: def2-2
    VAR_hoge3: def2-3
