- name: set_fact
  set_fact:
    randstatus: "{{ 10 | random }}"
- name: pause
  command: sleep "{{ randstatus }}"
- name: display data
  shell: echo {{ item }} >> /tmp/test.txt
  with_items: "{{ VAR_test1 }}__"
