- name: display data1
  shell: echo {{ VAR_test1 }} >> /tmp/test.txt

- name: display data2
  shell: echo {{ item }} >> /tmp/test.txt
  with_items: "{{ VAR_test2 }}"

- name: display data3
  shell:
    echo "{{ item.test3_1 }}a" >> /tmp/test.txt;
    echo "{{ item.test3_2 }}a" >> /tmp/test.txt;
    echo "{{ item.test3_3 }}a" >> /tmp/test.txt;
  with_items: "{{ VAR_test3 }}"

